### ISSUE TITLE
Release candidates

### ISSUE THREAD

**Issue by wpalfi** [conan-community/conan-cmake-installer#11]
Would be great to have release candidate packages. We have projects that require CMake 3.11, but we dont want to install it as long as it is not released. I guess that should be simple?

**Comment by lasote** [comment]
As long as the version is correctly identified, I don't have anything against including them, except the time to implement it, but contributions are welcomed.

**Comment by wpalfi** [comment]
I tried it on Windows and it worked without modifications. 
python 2.7
conan 1.0.4
conan-package tools 0.13.0
CMake 3.11.0-rc1

**Comment by wpalfi** [comment]
PR #12

**Comment by danimtb** [comment]
Already done in the referenced PR. Thanks!
