### ISSUE TITLE
Why enforce x86 binary distribution on Linux x86_64?

### ISSUE THREAD

**Issue by torbjoernk** [conan-community/conan-cmake-installer#13]
Why does this recipe enforce the 32bit binary distribution for 64bit Linux?
```
def get_filename(self):
    os_id = {"Macos": "Darwin", "Windows": "win32"}.get(str(self.os),
                                                        str(self.os))
    arch_id = {"x86": "i386"}.get(self.arch, self.arch) if self.os != "Windows" else "x86"
    if self.os == "Linux" and self.cmake_version in ("2.8.12", "3.0.2") and \
        self.arch == "x86_64":
        arch_id = "i386"
    if self.os == "Macos" and self.cmake_version == "2.8.12":
        arch_id = "universal"
    return "cmake-%s-%s-%s" % (self.cmake_version, os_id, arch_id)
```

There is a x86_64 binary distribution available at least for a couple newer version. c.f. https://cmake.org/files/v3.10/cmake-3.10.2-Linux-x86_64.tar.gz

**Comment by db4** [comment]
It does that for old versions only (2.8.12" and "3.0.2). Why this is a problem?

**Comment by danimtb** [comment]
There are no cmake-2.8.12-Linux-x86_64 nor cmake-3.0.2-Linux-x86_64 binaries available for download.

Please check https://cmake.org/files/v2.8/ and https://cmake.org/files/v3.0/

Thanks!
